// protoc --go_out=. --go_opt=paths=source_relative     --go-grpc_out=. --go-grpc_opt=paths=source_relative pkg/v2-apis/be/proto/service.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: pkg/v2-apis/be/service/service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_pkg_v2_apis_be_service_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_v2_apis_be_service_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_pkg_v2_apis_be_service_service_proto_rawDescGZIP(), []int{0}
}

func (x *StoreRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StoreRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_pkg_v2_apis_be_service_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_v2_apis_be_service_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_pkg_v2_apis_be_service_service_proto_rawDescGZIP(), []int{1}
}

func (x *StoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_v2_apis_be_service_service_proto protoreflect.FileDescriptor

const file_pkg_v2_apis_be_service_service_proto_rawDesc = "" +
	"\n" +
	"$pkg/v2-apis/be/service/service.proto\x12\aservice\"2\n" +
	"\fStoreRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\")\n" +
	"\rStoreResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2J\n" +
	"\x0eExampleService\x128\n" +
	"\x05Store\x12\x15.service.StoreRequest\x1a\x16.service.StoreResponse\"\x00B\vZ\t./serviceb\x06proto3"

var (
	file_pkg_v2_apis_be_service_service_proto_rawDescOnce sync.Once
	file_pkg_v2_apis_be_service_service_proto_rawDescData []byte
)

func file_pkg_v2_apis_be_service_service_proto_rawDescGZIP() []byte {
	file_pkg_v2_apis_be_service_service_proto_rawDescOnce.Do(func() {
		file_pkg_v2_apis_be_service_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_v2_apis_be_service_service_proto_rawDesc), len(file_pkg_v2_apis_be_service_service_proto_rawDesc)))
	})
	return file_pkg_v2_apis_be_service_service_proto_rawDescData
}

var file_pkg_v2_apis_be_service_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_v2_apis_be_service_service_proto_goTypes = []any{
	(*StoreRequest)(nil),  // 0: service.StoreRequest
	(*StoreResponse)(nil), // 1: service.StoreResponse
}
var file_pkg_v2_apis_be_service_service_proto_depIdxs = []int32{
	0, // 0: service.ExampleService.Store:input_type -> service.StoreRequest
	1, // 1: service.ExampleService.Store:output_type -> service.StoreResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_v2_apis_be_service_service_proto_init() }
func file_pkg_v2_apis_be_service_service_proto_init() {
	if File_pkg_v2_apis_be_service_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_v2_apis_be_service_service_proto_rawDesc), len(file_pkg_v2_apis_be_service_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_v2_apis_be_service_service_proto_goTypes,
		DependencyIndexes: file_pkg_v2_apis_be_service_service_proto_depIdxs,
		MessageInfos:      file_pkg_v2_apis_be_service_service_proto_msgTypes,
	}.Build()
	File_pkg_v2_apis_be_service_service_proto = out.File
	file_pkg_v2_apis_be_service_service_proto_goTypes = nil
	file_pkg_v2_apis_be_service_service_proto_depIdxs = nil
}
