# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Start Servers
      run: make servers

    - name: Start Client
      run: make client | sed '1,3d' | cut -f3- -d' ' > /tmp/fe-be-db.result

    - name: Integration Test 
      run: diff /tmp/fe-be-db.result test/fe-be-db.result

    - name: Stop Servers
      run: make stop
