# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  unit-test-and-build:
    name: Unit Tests & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Build Binaries
        run: make build

      - name: Run Unit Tests
        run: make test

  integration-test:
    name: Docker Compose Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Install Go Binaries to PATH
        run: |
          make install-servers
          make install-client-fe
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: Set up Go
  #     uses: actions/setup-go@v5
  #     with:
  #       go-version: '1.25'
  #       cache: true

  #   - name: Build
  #     run: make build

  #   - name: Test
  #     run: make test

  #   - name: Start Servers 
  #     run: make servers

  #   - name: Integration Test 
  #     run: make itests

  #   - name: Stop Servers
  #     run: make stop
